### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by saurabhnsonar** [erxes/erxes#245]
Hi,

I was testing the environment, as I wish to continue some development on this project but I am unable to get it worked on my system.

I get error for websocket in console logs:

`WebSocket connection to 'ws://localhost:3300/subscriptions' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Also for graphql:

`networkInterface.js:103 OPTIONS http://localhost:3300/graphql net::ERR_CONNECTION_REFUSED
./node_modules/apollo-client/transport/networkInterface.js.HTTPFetchNetworkInterface.fetchFromRemoteEndpoint @ networkInterface.js:103
(anonymous) @ networkInterface.js:118
Promise resolved (async)
./node_modules/apollo-client/transport/networkInterface.js.HTTPFetchNetworkInterface.query @ networkInterface.js:118
(anonymous) @ QueryManager.js:126
./node_modules/apollo-client/core/QueryManager.js.QueryManager.mutate @ QueryManager.js:124
./node_modules/apollo-client/ApolloClient.js.ApolloClient.mutate @ ApolloClient.js:197
GraphQL.dataForChildViaMutation @ react-apollo.browser.umd.js:544
login @ SignIn.js:16
login @ SignIn.js:30
callCallback @ react-dom.development.js:1299
invokeGuardedCallbackDev @ react-dom.development.js:1338
invokeGuardedCallback @ react-dom.development.js:1195
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:1209
executeDispatch @ react-dom.development.js:1432
executeDispatchesInOrder @ react-dom.development.js:1454
executeDispatchesAndRelease @ react-dom.development.js:1969
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:1980
forEachAccumulated @ react-dom.development.js:1946
processEventQueue @ react-dom.development.js:2139
runEventQueueInBatch @ react-dom.development.js:2151
handleTopLevel @ react-dom.development.js:2161
handleTopLevelImpl @ react-dom.development.js:1800
batchedUpdates @ react-dom.development.js:13238
performFiberBatchedUpdates @ react-dom.development.js:1646
stackBatchedUpdates @ react-dom.development.js:1637
batchedUpdates @ react-dom.development.js:1651
batchedUpdatesWithControlledComponents @ react-dom.development.js:1664
dispatchEvent @ react-dom.development.js:1874
SignIn.js:29 Error: Network error: Failed to fetch
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:183
    at <anonymous>`

I tried playing with the ports, but nothing sorted out. Removed few code issue but still the same. 

FYI: I am using redesign-ui branch.

**Comment by mendorshikh** [comment]
@saurabhnsonar Hello there, currently we are very close to lunch 1.0 with new UI. I wish u wait a bit and continue your things after we lunch. 

@batamar can u give a comment on his issue. tnx

**Comment by saurabhnsonar** [comment]
@mendorshikh Thanks for your information. Is this project development active? As I wish to contribute in it.

**Comment by mendorshikh** [comment]
@saurabhnsonar Oh hell yeah! We are developing very hard :) I was think to respond your email too.

**Comment by saurabhnsonar** [comment]
@mendorshikh That is great. oh, yes I already dropped the mail couple of days before. I have a company was previously working on different projects for clients. But actively working now on our own project for some hyperlocal marketplace. So, was looking forward to contribute in this in my spare time. :)

**Comment by mendorshikh** [comment]
@saurabhnsonar Thats awesome! I will personally let u know once we finish some stuff.

**Comment by saurabhnsonar** [comment]
@mendorshikh Any update on this? As I cannot install it locally. Or you suggest me to wait for some days?

**Comment by mendorshikh** [comment]
@saurabhnsonar Hello there. 

I suggest u to wait until Nov 30. We have updated both UI and backend. Currently, we are debugging. To give u an update, check out screenshots I attached.

![screen shot 2017-11-13 at 3 57 22 pm 2](https://user-images.githubusercontent.com/1748857/32715064-8cec4d42-c88b-11e7-9f73-af336d934cbb.png)

**Comment by saurabhnsonar** [comment]
Wow this looks awesome, I will definitely wait for it. 😄 🎉

**Comment by mendorshikh** [comment]
@saurabhnsonar Glad u liked it! :)

**Comment by mendorshikh** [comment]
Hello @saurabhnsonar erxes 0.9 is out. We fixed issues u had trouble. Check it out! Hope u enjoy! Please let us know.

**Comment by saurabhnsonar** [comment]
Yes, I am already checking all your updates and installed 0.9.0 version too. I am confused as I am unable to find settings.json file on this version for credentials. Also adding settings.json file of earlier version is not working. Maybe I am doing something wrong.

**Comment by saurabhnsonar** [comment]
@mendorshikh Yes, I am already checking all your updates and installed 0.9.0 version too. I am confused as I am unable to find settings.json file on this version for credentials. Also adding settings.json file of earlier version is not working. Maybe I am doing something wrong. As per update of yesterday, I am still unable to find the credentials in .env.development. :P Sorry to trouble you again.

**Comment by shinebayar-g** [comment]
Hello @saurabhnsonar ,

I hope you're doing great.
Quick update here, if you want to try out erxes again:

I've updated our docker images, please take a look at here.
https://hub.docker.com/u/erxes/

Read instructions at https://github.com/erxes/erxes/wiki/Use-erxes-with-Docker page. If you have any questions feel free to ask here or open a new issue.
